'use strict';
const assert = require('node:assert/strict');
const harness = require('./harness.cjs');
const calls = (page, method) => page.evaluate((name) => window.__calls.filter((call) => call.method === name).map((call) => call.value), method);
(async () => {
  const app = await harness();
  try {
    const page = await app.page('expanded', { clipboardToolsEnabled: false, entries: 4, hosts: 2 });
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    const dialog = page.getByRole('dialog', { name: 'ShelfDock settings' });
    const syncSwitch = dialog.getByRole('switch', { name: 'Sync between devices', exact: true });
    const connect = dialog.getByRole('button', { name: 'Connect device', exact: true });
    const machine = dialog.getByRole('combobox', { name: 'Machine', exact: true });
    const direction = dialog.getByRole('combobox', { name: 'Direction', exact: true });
    const history = dialog.getByRole('radio', { name: 'Save to clipboard history', exact: true });
    const systemClipboard = dialog.getByRole('radio', { name: 'Also place on the system clipboard', exact: true });
    await dialog.waitFor();
    await dialog.getByText('Advanced clipboard sync', { exact: true }).click();
    assert.equal(await page.evaluate(() => [document.documentElement, document.body].every((surface) => surface.classList.contains('platform-darwin') && surface.classList.contains('liquid-glass'))), true);
    await page.evaluate(() => { window.__state.environment.nativeGlass = { mode: 'solid', reducedTransparency: true }; window.__listeners.state(structuredClone(window.__state)); });
    await page.waitForFunction(() => !document.documentElement.classList.contains('liquid-glass'));
    assert.equal(await page.evaluate(() => [document.documentElement, document.body].every((surface) => surface.classList.contains('platform-darwin') && !surface.classList.contains('liquid-glass'))), true, 'Reduced transparency removes glass while retaining Mac layout');
    await page.evaluate(() => { window.__state.environment.nativeGlass = { mode: 'native' }; window.__listeners.state(structuredClone(window.__state)); });
    await page.waitForFunction(() => document.documentElement.classList.contains('liquid-glass'));
    assert.equal(await syncSwitch.getAttribute('aria-checked'), 'false');
    for (const control of [syncSwitch, connect, machine, direction, history, systemClipboard]) assert.equal(await control.isDisabled(), true);
    assert.equal(await history.isChecked(), true);
    assert.equal(await direction.inputValue(), 'both');
    assert.deepEqual(await direction.locator('option').allTextContents(), ['Send only', 'Receive only', 'Both directions']);
    assert.deepEqual(await machine.locator('option').allTextContents(), ['Choose a machine', 'Studio', 'Work laptop']);
    assert.equal(await dialog.getByRole('button', { name: 'Allow pairing', exact: true }).count(), 0);
    assert.equal(await dialog.getByRole('textbox', { name: /Pairing code/ }).count(), 0);
    assert.equal(await dialog.getByText('Turn on Clipboard tools before connecting devices.', { exact: true }).isVisible(), true);
    await page.evaluate(() => {
      const publish = () => structuredClone(window.__state);
      const sync = () => window.__state.clipboardSync ||= { available: true, enabled: false, paused: false, receiveMode: 'history', peers: [] };
      window.drift.updateClipboardSync = async (value) => { window.__calls.push({ method: 'updateClipboardSync', value }); Object.assign(sync(), value); return publish(); };
      window.drift.pairOwnedClipboardSync = async (value) => {
        window.__calls.push({ method: 'pairOwnedClipboardSync', value });
        await new Promise((resolve) => { window.__finishConnect = resolve; });
        if (window.__connectError) throw new Error(window.__connectError);
        sync().error = '';
        sync().peers = [...sync().peers.filter((peer) => peer.id !== 'peer-studio'), { id: 'peer-studio', label: 'Studio', direction: value.direction, paused: false, status: 'connected', hostLabel: 'Studio' }];
        return { ...publish(), clipboardLinkedPeerId: 'peer-studio' };
      };
      window.drift.updateClipboardPeer = async (value) => { window.__calls.push({ method: 'updateClipboardPeer', value }); sync().peers = sync().peers.map((peer) => peer.id === value.id ? { ...peer, ...value } : peer); return publish(); };
      window.drift.revokeClipboardPeer = async (value) => { window.__calls.push({ method: 'revokeClipboardPeer', value }); sync().peers = sync().peers.filter((peer) => peer.id !== value.id); return publish(); };
    });
    await dialog.getByRole('switch', { name: 'Enable Clipboard tools', exact: true }).click();
    await page.waitForFunction(() => !document.querySelector('[aria-label="Sync between devices"]').disabled);
    assert.equal(await syncSwitch.getAttribute('aria-checked'), 'false', 'Tools do not enable sync');
    assert.equal(await connect.isDisabled(), true);
    assert.equal(await history.isEnabled(), true);
    await syncSwitch.click();
    await machine.selectOption('host-0');
    await direction.selectOption('receive');
    assert.deepEqual(await calls(page, 'pairOwnedClipboardSync'), [], 'Selection never starts a connection');
    assert.equal(await connect.isEnabled(), true);
    await connect.focus();
    await connect.press('Enter');
    const connecting = dialog.getByRole('button', { name: 'Connecting…', exact: true });
    await connecting.waitFor();
    assert.equal(await connecting.getAttribute('aria-busy'), 'true');
    assert.equal(await connecting.isDisabled(), true);
    assert.equal(await machine.isDisabled(), true);
    assert.equal(await direction.isDisabled(), true);
    assert.deepEqual(await calls(page, 'pairOwnedClipboardSync'), [{ hostId: 'host-0', direction: 'receive' }]);
    await page.evaluate(() => { window.__connectError = 'Open ShelfDock on Studio and enable Clipboard tools and sync, then try again.'; window.__finishConnect(); });
    await dialog.getByRole('alert').filter({ hasText: 'Open ShelfDock on Studio' }).waitFor();
    assert.equal(await connect.isEnabled(), true, 'Failed connections can be retried');
    assert.equal(await page.locator('.toast').count(), 0, 'Connection errors stay inline');
    await page.evaluate(() => { window.__connectError = ''; });
    await connect.click();
    await connecting.waitFor();
    await page.evaluate(() => window.__finishConnect());
    await dialog.getByRole('status').filter({ hasText: 'Connected to Studio.' }).waitFor();
    assert.equal(await dialog.getByRole('status', { name: 'Studio: Connected', exact: true }).getAttribute('aria-live'), 'polite');
    assert.equal(await dialog.getByRole('alert').count(), 0);
    await page.evaluate(() => {
      window.__state.hosts[1].name = 'Studio';
      window.__state.clipboardSync.peers.unshift({ id: 'older-same-name', label: 'Studio', hostLabel: 'Studio', direction: 'both', paused: false, status: 'connected' });
      window.__listeners.state(structuredClone(window.__state));
    });
    await machine.selectOption('host-1');
    await connect.click();
    await connecting.waitFor();
    await page.evaluate(() => window.__finishConnect());
    await dialog.getByRole('status').filter({ hasText: 'Connected to Studio.' }).waitFor();
    await page.evaluate(() => {
      window.__state.clipboardSync.peers.find((peer) => peer.id === 'peer-studio').status = 'offline';
      window.__listeners.state(structuredClone(window.__state));
    });
    await dialog.getByRole('status').filter({ hasText: 'Connected to Studio.' }).waitFor({ state: 'hidden' });
    assert.equal(await dialog.getByRole('status', { name: 'Studio: Connected', exact: true }).count(), 1, 'The older same-name peer remains connected without keeping the new link confirmation alive');
    await page.evaluate(() => {
      window.__state.clipboardSync.peers = window.__state.clipboardSync.peers.filter((peer) => peer.id !== 'older-same-name');
      window.__state.clipboardSync.peers[0].status = 'connected';
      window.__listeners.state(structuredClone(window.__state));
    });
    await dialog.getByRole('button', { name: 'Pause clipboard sync', exact: true }).click();
    await dialog.getByRole('button', { name: 'Resume clipboard sync', exact: true }).waitFor();
    for (const control of [connect, machine, direction]) assert.equal(await control.isDisabled(), true);
    assert.equal(await dialog.getByText('Paused on this computer', { exact: true }).isVisible(), true);
    await dialog.getByRole('button', { name: 'Resume clipboard sync', exact: true }).click();
    await connect.waitFor({ state: 'visible' });
    await page.waitForFunction(() => !document.querySelector('[aria-label="Machine"]').disabled);
    await page.evaluate(() => { window.__state.clipboardSync.available = false; window.__listeners.state(structuredClone(window.__state)); });
    await page.waitForFunction(() => document.querySelector('[aria-label="Machine"]').disabled);
    assert.equal(await connect.isDisabled(), true);
    assert.equal(await dialog.getByRole('status').filter({ hasText: 'A secure system store is unavailable.' }).isVisible(), true);
    await page.evaluate(() => { window.__state.clipboardSync.available = true; window.__state.clipboardSync.pairing = { code: 'ABCDEFGH', expiresAt: new Date(Date.now() + 300000).toISOString() }; window.__listeners.state(structuredClone(window.__state)); });
    await page.waitForFunction(() => !document.querySelector('[aria-label="Machine"]').disabled);
    assert.equal(await dialog.getByText('ABCDEFGH', { exact: true }).count(), 0, 'Legacy pairing state does not expose code UI');
    await dialog.getByRole('combobox', { name: 'Direction for Studio', exact: true }).selectOption('send');
    await dialog.getByRole('button', { name: 'Pause sync with Studio', exact: true }).click();
    assert.equal(await dialog.getByText('Paused here', { exact: true }).isVisible(), true);
    await dialog.getByRole('button', { name: 'Resume sync with Studio', exact: true }).click();
    assert.deepEqual(await calls(page, 'updateClipboardPeer'), [{ id: 'peer-studio', direction: 'send' }, { id: 'peer-studio', paused: true }, { id: 'peer-studio', paused: false }]);
    await page.evaluate(() => { window.__state.clipboardSync.peers[0].status = 'offline'; window.__listeners.state(structuredClone(window.__state)); });
    await dialog.getByRole('status', { name: 'Studio: Offline', exact: true }).waitFor();
    await dialog.getByRole('button', { name: 'Revoke', exact: true }).click();
    assert.deepEqual(await calls(page, 'revokeClipboardPeer'), [{ id: 'peer-studio' }]);
    await history.focus();
    await history.press('ArrowDown');
    await page.waitForFunction(() => window.__calls.some((call) => call.method === 'updateClipboardSync' && call.value.receiveMode === 'clipboard'));
    assert.equal(await systemClipboard.isChecked(), true);
    await syncSwitch.focus();
    await syncSwitch.press('Space');
    await page.waitForFunction(() => document.querySelector('[aria-label="Sync between devices"]').getAttribute('aria-checked') === 'false');
    assert.equal(await connect.isDisabled(), true);
    assert.equal(await page.locator('.toast').count(), 0);
    assert.deepEqual(await calls(page, 'captureClipboard'), [], 'Connecting never captures the clipboard');
    assert.deepEqual(page.errors, []);
    await page.evaluate(() => { window.__clips.entries[0].sourceLabel = 'Studio'; });
    await page.keyboard.press('Escape');
    await dialog.waitFor({ state: 'hidden' });
    await page.getByRole('button', { name: 'Clipboard', exact: true }).click();
    await page.locator('.clipboard-source').waitFor();
    assert.equal((await page.locator('.clipboard-source').innerText()).trim(), 'From Studio');
    const sourceRow = page.locator('.clipboard-entry').filter({ has: page.locator('.clipboard-source') });
    assert.match(await sourceRow.getAttribute('aria-label'), /Project handoff notes/);
    assert.equal(await page.locator('.clipboard-entry').nth(1).locator('.clipboard-source').count(), 0);
    assert.deepEqual(page.errors, []);
    console.log('Clipboard sync: explicit own-device SSH connection, off/paused gates, inline progress/error/retry, direction, receive preference, and peer management.');
    await page.close();
  } finally { await app.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
