'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');
const harness=require('./harness.cjs');
const count=(page,method)=>page.evaluate(method=>window.__calls.filter(call=>call.method===method).length,method);
const drop=async(page,selector,data)=>{
  const transfer=await page.evaluateHandle(data=>{const transfer=new DataTransfer();for(const [type,value] of Object.entries(data))transfer.setData(type,value);return transfer;},data);
  await page.locator(selector).dispatchEvent('drop',{dataTransfer:transfer});await transfer.dispose();
};
(async()=>{const app=await harness();try{
  for(const mode of ['compact','expanded','large']){
    const page=await app.page(mode);
    assert.equal(await page.getByLabel('Display density',{exact:true}).inputValue(),mode);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    const card=page.locator('[data-host-id="host-0"]');
    const height=await card.locator('.machine-summary').evaluate(el=>el.getBoundingClientRect().height);
    assert.ok(mode==='compact'?height<=45:height<=75,`wrong ${mode} row height ${height}`);
    assert.equal(await page.getByRole('button',{name:/Machines 12 · 8 ready/}).count(),1);
    await page.getByRole('button',{name:/^Select Studio,/}).focus();
    if(mode==='compact')assert.equal(await card.locator('.machine-actions').evaluate(el=>getComputedStyle(el).opacity),'1');
    await page.keyboard.press('Shift+F10');await page.getByRole('menu',{name:'Machine connections'}).waitFor();
    await page.keyboard.press('Escape');assert.equal(await count(page,'hideWindow'),0);
    await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await card.locator('.tiny-dot.ready').evaluate(el=>getComputedStyle(el).animationName),'none');
    await page.close();
  }
  const expanded=await app.page('large');
  const first=expanded.locator('[data-host-id="host-0"]');const second=expanded.locator('[data-host-id="host-1"]');
  await second.getByLabel('Website address',{exact:true}).fill('http://localhost:9999');
  await first.getByRole('button',{name:'Connections for Studio',exact:true}).click();
  await expanded.getByRole('menuitem',{name:/Remote port forward/}).click();
  assert.equal(await first.getByRole('button',{name:'← Remote',exact:true}).getAttribute('aria-pressed'),'true');
  assert.equal(await second.getByRole('button',{name:'Local →',exact:true}).getAttribute('aria-pressed'),'true');
  assert.equal(await second.getByLabel('Website address',{exact:true}).inputValue(),'http://localhost:9999');
  await expanded.getByRole('button',{name:'Close machines',exact:true}).click();
  await expanded.getByRole('button',{name:'Clipboard',exact:true}).click();
  await expanded.getByText('Recording locally',{exact:true}).waitFor();
  assert.equal(await expanded.evaluate(()=>window.__calls.filter(c=>c.method==='setInteraction').at(-1).value.editing),false);
  assert.deepEqual(expanded.errors,[]);await expanded.close();
  const overflow=await app.page('expanded');
  await overflow.evaluate(()=>{window.__tunnels.active=[1331,1442,1553].map((port,i)=>({id:'live-'+i,hostId:'host-0',hostName:'Studio',mode:'local',targetHost:'localhost',targetPort:port,listenPort:port,status:'running'}));window.__publishTunnels();});
  await overflow.getByRole('button',{name:'View all 3 forwards on Studio',exact:true}).click();
  await overflow.getByRole('dialog',{name:'Port forwarding'}).waitFor();
  assert.equal(await overflow.getByRole('button',{name:'Stop forward',exact:true}).count(),3);
  await overflow.close();
  const page=await app.page('expanded');const card=page.locator('[data-host-id="host-0"]');
  await card.getByRole('button',{name:'Open site on Studio',exact:true}).click();
  const form=card.getByRole('form',{name:'Connect to a website through Studio'});
  await form.waitFor();assert.equal(await form.getByRole('button',{name:'Advanced',exact:true}).getAttribute('aria-expanded'),'false');
  assert.equal(await form.getByLabel('Website address',{exact:true}).inputValue(),'');
  assert.equal(await count(page,'startTunnel'),0);
  await page.locator('.app').dispatchEvent('dragenter');
  await drop(page,'[data-host-id="host-0"] .quick-url-input',{'text/plain':'http://localhost:1331/review?token=transient#section'});
  assert.equal(await page.locator('.app.is-dragging').count(),0);
  assert.equal(await count(page,'send'),0);assert.equal(await count(page,'enqueueText'),0);
  assert.equal(await form.getByLabel('Website address',{exact:true}).inputValue(),'http://localhost:1331/review?token=transient#section');
  await form.getByRole('button',{name:'Go: connect website'}).click();
  await page.waitForFunction(()=>window.__calls.some(call=>call.method==='openTunnelSite'));
  const request=await page.evaluate(()=>window.__calls.find(call=>call.method==='startTunnel').value);
  assert.deepEqual(request,{hostId:'host-0',mode:'local',targetHost:'localhost',targetPort:1331,listenPort:1331,remember:true,note:''});
  assert.deepEqual(await page.evaluate(()=>window.__calls.find(call=>call.method==='openTunnelSite').value),{id:await page.evaluate(()=>window.__tunnels.active[0].id),scheme:'http:',path:'/review?token=transient#section'});
  assert.equal(await page.evaluate(()=>Object.values(localStorage).some(value=>value.includes('transient'))),false);
  await page.screenshot({path:path.resolve(__dirname,'../../docs/ui/after-quick-connect-live.png')});
  await card.getByRole('button',{name:'Stop local forward on Studio port 1331',exact:true}).click();
  await page.waitForFunction(()=>window.__tunnels.active.length===0);
  if(await card.getByRole('button',{name:'Close quick connect',exact:true}).count())await card.getByRole('button',{name:'Close quick connect',exact:true}).click();
  await card.getByRole('button',{name:'Open site on Studio',exact:true}).click();
  await page.waitForFunction(()=>window.__calls.some(call=>call.method==='restartTunnel'));
  assert.equal(await count(page,'startTunnel'),1);
  await card.getByRole('button',{name:'Open site on Studio',exact:true}).click();
  assert.equal(await count(page,'restartTunnel'),1); // Existing live site opens without another session.
  await card.getByRole('button',{name:'Stop local forward on Studio port 1331',exact:true}).click();
  await card.getByRole('button',{name:'Connections for Studio',exact:true}).click();
  await page.getByRole('menuitem',{name:/Remote port forward/}).click();
  await form.getByRole('button',{name:'← Remote',exact:true}).waitFor();
  assert.equal(await form.getByRole('button',{name:'← Remote',exact:true}).getAttribute('aria-pressed'),'true');
  await form.getByLabel('Website address',{exact:true}).fill('http://service.example.test:4000');
  await form.getByLabel('Listening port',{exact:true}).fill('14000');
  const opensBefore=await count(page,'openTunnelSite');
  await form.getByRole('button',{name:'Go: connect website'}).click();
  await page.waitForFunction(()=>window.__tunnels.active.some(entry=>entry.mode==='remote'));
  assert.equal(await count(page,'openTunnelSite'),opensBefore);
  assert.equal(await form.getByLabel('Local website address',{exact:true}).count(),0);
  await card.getByRole('button',{name:'Stop remote forward on Studio port 14000',exact:true}).click();
  if(await card.getByRole('button',{name:'Close quick connect',exact:true}).count())await card.getByRole('button',{name:'Close quick connect',exact:true}).click();
  // A deliberate machine drop still sends precisely the held shelf item, without forwarding.
  const startsBefore=await count(page,'startTunnel');
  await drop(page,'[data-host-id="host-0"]',{'application/x-drift-items':JSON.stringify(['item-1'])});
  await page.waitForFunction(()=>window.__calls.some(call=>call.method==='send'));
  assert.deepEqual(await page.evaluate(()=>window.__calls.find(call=>call.method==='send').value),{hostId:'host-0',itemIds:['item-1']});
  assert.equal(await count(page,'startTunnel'),startsBefore);
  await page.getByRole('button',{name:'Clear shelf',exact:true}).click();
  await page.getByRole('button',{name:'Undo clear shelf',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.__state.items.length),2);
  await page.getByRole('button',{name:'Deselect',exact:true}).click();
  await page.getByRole('button',{name:'Select Release notes.txt',exact:true}).click();
  await page.getByLabel('Include Studio in batch transfer').check();await page.getByLabel('Include Work laptop in batch transfer').check();
  await page.getByRole('button',{name:'Review & send',exact:true}).click();
  assert.equal(await count(page,'sendMany'),0);
  await page.getByRole('button',{name:'Send 1 item to 2 machines',exact:true}).click();
  assert.deepEqual(await page.evaluate(()=>window.__calls.find(call=>call.method==='sendMany').value),{hostIds:['host-0','host-1'],itemIds:['item-1']});
  assert.deepEqual(page.errors,[]);await page.close();
  const pending=await app.page('expanded');const target=pending.locator('[data-host-id="host-0"]');
  await pending.evaluate(()=>{window.__deferStart=true;});await target.getByRole('button',{name:'Open site on Studio'}).click();
  await target.getByLabel('Website address',{exact:true}).fill('http://localhost:1331');await target.getByRole('button',{name:'Go: connect website'}).click();
  await target.getByRole('button',{name:'Stop local forward on Studio port 1331',exact:true}).click();
  await pending.evaluate(()=>window.__finishStale());
  await pending.waitForFunction(()=>!document.querySelector('.quick-url-input').disabled);
  assert.equal(await target.locator('.live-forward-chip').count(),0);assert.equal(await count(pending,'openTunnelSite'),0);
  await pending.evaluate(()=>{window.__deferStart=false;window.__failStart=true;});
  await target.getByRole('button',{name:'Go: connect website'}).click();
  await target.getByRole('status').filter({hasText:'listening port is already in use'}).waitFor();
  assert.equal(await target.getByLabel('Website address',{exact:true}).inputValue(),'http://localhost:1331');
  assert.deepEqual(pending.errors,[]);await pending.close();
  console.log('Machine/quick-connect UI passed: three densities, keyboard/context menus, reduced motion, URL drop isolation, exact forwarding, one-click repeat/open, remote direction, pending Stop/stale replies, conflict feedback, shelf Undo and batch transfer.');
}finally{await app.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
