'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const harness = require('./harness.cjs');
const fixture = require('./update-fixture.cjs');
const screenshotDirectory = path.resolve(__dirname, '../../docs/v050');
const openUpdates = async page => {
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('button', { name: /^(Manage updates|Update available|Update ready)$/ }).click();
  await page.getByRole('dialog', { name: 'Updates', exact: true }).waitFor();
  await page.getByText('Installed version 0.5.0', { exact: true }).waitFor();
};
const calls = (page, method) => page.evaluate(method => window.__updateCalls.filter(call => call.method === method).length, method);
const verifyBounds = async page => {
  const box = await page.getByRole('dialog', { name: 'Updates', exact: true }).boundingBox();
  const viewport = page.viewportSize();
  assert.ok(box.x >= 0 && box.y >= 0 && box.x + box.width <= viewport.width + 1 && box.y + box.height <= viewport.height + 1, 'Updates dialog stays within the viewport');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'No horizontal body overflow');
  await page.getByRole('button', { name: 'Done', exact: true }).scrollIntoViewIfNeeded();
  const done = await page.getByRole('button', { name: 'Done', exact: true }).boundingBox();
  assert.ok(done.y >= 0 && done.y + done.height <= viewport.height + 1, 'Bottom actions can be reached by scrolling');
};

(async () => {
  const app = await harness();
  const passed = [];
  await fs.mkdir(screenshotDirectory, { recursive: true });
  try {
    for (const [mode, name] of [['compact', 'compact'], ['expanded', 'balanced'], ['large', 'expanded']]) {
      const page = await app.page(mode, { clipboardToolsEnabled: false });
      await page.emulateMedia({ reducedMotion: 'reduce' });
      await page.evaluate(fixture);
      const received = page.getByRole('navigation', { name: 'Workspace' }).getByRole('button', { name: /^Received/ });
      const initialReceivedLabel = await received.innerText();
      await openUpdates(page);
      assert.equal(await calls(page, 'checkForUpdates'), 0, 'Opening updates never performs an unrequested check');
      const autoCheck = page.getByRole('checkbox', { name: /^Check automatically/ });
      const autoDownload = page.getByRole('checkbox', { name: /^Download updates in the background/ });
      assert.equal(await autoCheck.isChecked(), false); assert.equal(await autoDownload.isChecked(), false); assert.equal(await autoDownload.isDisabled(), true);
      await autoCheck.check(); await autoDownload.check();
      assert.equal(await autoDownload.isChecked(), true);
      await autoCheck.uncheck(); assert.equal(await autoDownload.isChecked(), false); assert.equal(await autoDownload.isDisabled(), true);
      await page.getByRole('button', { name: 'Check for updates', exact: true }).click();
      await page.getByText('Version 0.5.1 is available.', { exact: true }).waitFor();
      assert.equal(await calls(page, 'checkForUpdates'), 1);
      await verifyBounds(page);
      await page.locator('.updates-installed').scrollIntoViewIfNeeded();
      await page.screenshot({ path: path.join(screenshotDirectory, name + '-updates.png') });
      await page.getByRole('button', { name: 'Done', exact: true }).click();
      assert.equal(await page.getByRole('button', { name: 'Clipboard', exact: true }).count(), 0, 'Updates do not enable Clipboard');
      assert.equal(await received.innerText(), initialReceivedLabel, 'Opening and closing Updates leaves the Received badge unchanged');
      assert.equal(await page.getByLabel('Update available', { exact: true }).count(), 1, 'Settings badge retains available update state after closing');
      await page.screenshot({ path: path.join(screenshotDirectory, name + '-transfers.png') });
      await received.click(); await page.getByRole('region', { name: 'Received and sent files' }).waitFor();
      await page.screenshot({ path: path.join(screenshotDirectory, name + '-received.png') });
      await page.getByRole('button', { name: 'Settings', exact: true }).click();
      await page.getByRole('switch', { name: 'Enable Clipboard tools', exact: true }).click();
      await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
      await page.getByRole('navigation', { name: 'Workspace' }).getByRole('button', { name: 'Clipboard', exact: true }).click();
      await page.locator('.clipboard-list [role="option"]').first().waitFor();
      assert.equal(await page.getByRole('navigation', { name: 'Workspace' }).getByRole('button', { name: 'Clipboard', exact: true }).getAttribute('aria-current'), 'page');
      await page.screenshot({ path: path.join(screenshotDirectory, name + '-clipboard.png') });
      assert.deepEqual(page.errors, []); await page.close();
      passed.push(name + ': preferences, explicit checking, modal bounds, scroll reachability, badges, clipboard consent and screenshots');
    }

    const download = await app.page('expanded', { clipboardToolsEnabled: false });
    await download.evaluate(fixture, { status: 'available' });
    await openUpdates(download);
    await download.getByRole('button', { name: /^Download 12/ }).click();
    await download.getByRole('progressbar', { name: 'Update download progress' }).waitFor();
    assert.equal(await download.getByRole('progressbar', { name: 'Update download progress' }).getAttribute('value'), '25');
    await download.getByRole('button', { name: 'Close dialog', exact: true }).click();
    await openUpdates(download);
    await download.getByText('Downloading and verifying…', { exact: true }).waitFor();
    await download.getByRole('button', { name: 'Cancel', exact: true }).click();
    await download.getByRole('alert').filter({ hasText: 'Update operation cancelled.' }).waitFor();
    assert.equal(await calls(download, 'cancelUpdate'), 1);
    assert.equal(await download.getByRole('button', { name: 'Install update…', exact: true }).count(), 0);
    await download.getByRole('button', { name: /^Download 12/ }).click();
    await download.evaluate(() => window.__finishUpdateDownload('SHA-256 verification failed. No update was installed.'));
    await download.getByRole('alert').filter({ hasText: 'SHA-256 verification failed' }).waitFor();
    assert.equal(await calls(download, 'installUpdate'), 0);
    await download.getByRole('button', { name: /^Download 12/ }).click();
    await download.evaluate(() => window.__finishUpdateDownload());
    await download.getByText('Version 0.5.1 is ready.', { exact: true }).waitFor();
    await download.getByText('SHA-256 matched the published release.', { exact: true }).waitFor();
    assert.equal(await calls(download, 'installUpdate'), 0, 'Download does not install automatically');
    await download.getByRole('button', { name: 'Show download', exact: true }).click();
    assert.equal(await calls(download, 'revealUpdateDownload'), 1);
    await download.getByRole('button', { name: 'Install update…', exact: true }).click();
    await download.getByLabel('Review update installation', { exact: true }).waitFor();
    assert.equal(await calls(download, 'installUpdate'), 0, 'First install click only opens review');
    await download.evaluate(() => { window.__tunnels.active = [{ id: 'fictional-live', hostId: 'host-0', mode: 'local', listenPort: 1331, targetPort: 1331, targetHost: 'localhost', status: 'running' }]; window.__publishTunnels(); });
    await download.getByText('Finish active work and stop live forwards before restarting.', { exact: true }).waitFor();
    assert.equal(await download.getByRole('button', { name: 'Restart and install', exact: true }).isDisabled(), true);
    await download.evaluate(() => { window.__tunnels.active = []; window.__publishTunnels(); });
    await download.getByRole('button', { name: 'Restart and install', exact: true }).click();
    await download.getByText('Preparing your update…', { exact: true }).waitFor();
    assert.equal(await calls(download, 'installUpdate'), 1, 'Only the deliberate second click installs');
    await download.waitForFunction(() => document.querySelector('button[aria-label="Close dialog"]')?.disabled, null, { timeout: 2000 });
    assert.equal(await download.getByRole('button', { name: 'Close dialog', exact: true }).isDisabled(), true);
    await download.evaluate(() => window.__finishUpdateInstall('The destination changed. Use the verified package manually.'));
    await download.getByRole('alert').filter({ hasText: 'destination changed' }).waitFor();
    await download.waitForFunction(() => !document.querySelector('button[aria-label="Close dialog"]')?.disabled, null, { timeout: 2000 });
    assert.equal(await download.getByRole('button', { name: 'Close dialog', exact: true }).isDisabled(), false);
    assert.deepEqual(download.errors, []); await download.close();
    passed.push('Download survives panel closure; progress, cancel, checksum error, retry, explicit two-click install, live-forward guard and preparation error');

    const manual = await app.page('compact');
    await manual.evaluate(fixture, { status: 'downloaded', downloaded: true, installable: false, platform: 'linux' });
    await openUpdates(manual);
    await manual.getByText('Install this package manually', { exact: true }).waitFor();
    assert.equal(await manual.getByRole('button', { name: 'Install update…', exact: true }).count(), 0);
    await manual.getByText(/unpack this verified archive into a new folder you own/).waitFor();
    await verifyBounds(manual); assert.deepEqual(manual.errors, []); await manual.close();
    passed.push('Protected/unsupported installation keeps manual package instructions accessible');

    const personal = await app.page('expanded', { personalPreset: true, clipboardToolsEnabled: false });
    await personal.evaluate(fixture, { personal: true });
    await openUpdates(personal);
    await personal.getByRole('button', { name: 'Check for updates', exact: true }).click();
    await personal.getByRole('alert').filter({ hasText: /GitHub CLI.*gh auth login/ }).waitFor();
    assert.equal(await personal.getByRole('button', { name: /^Download / }).count(), 0);
    await personal.getByRole('button', { name: 'Private releases', exact: true }).click();
    assert.equal(await personal.evaluate(() => window.__openedUpdateUrl), 'https://github.com/LexiLominite/LexBridge-private/releases');
    assert.equal(await personal.evaluate(() => window.__updateCalls.every(call => call.repository === 'LexiLominite/LexBridge-private')), true);
    await personal.evaluate(() => { window.__privateUpdateAuthenticated = true; });
    await personal.getByRole('button', { name: 'Check for updates', exact: true }).click();
    await personal.getByText('Version 0.5.1 is available.', { exact: true }).waitFor();
    assert.equal(await personal.evaluate(() => window.__update.release.asset.name.startsWith('LexBridge-personal-')), true);
    assert.equal(await personal.evaluate(() => window.__updateCalls.some(call => call.repository === 'LexiLominite/ShelfDock')), false);
    assert.deepEqual(personal.errors, []); await personal.close();
    passed.push('Private update missing-CLI/auth guidance and authenticated retry keep the private repository and package edition');
    console.log('Updates UI: ' + passed.join('; ') + '.');
  } finally { await app.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
