'use strict';
const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const { Worker } = require('node:worker_threads');
const { pathToFileURL } = require('node:url');
const { parseFileURIs, isNonFileURIList, validateClipboardPNG } = require('./clipboard.cjs');
const DEFAULTS = Object.freeze({ enabled: false, paused: false, maxItems: 200, retentionDays: 30 });
const MAX_ITEM = 8 * 1024 * 1024, MAX_TEXT = 1024 * 1024, MAX_TOTAL = 32 * 1024 * 1024;
const MARKERS = ['application/x-nspasteboard-concealed-type', 'x-kde-passwordManagerHint', 'Clipboard Viewer Ignore', 'CanIncludeInClipboardHistory', 'CanUploadToCloudClipboard', 'org.nspasteboard.ConcealedType', 'org.nspasteboard.TransientType', 'org.nspasteboard.AutoGeneratedType', 'ExcludeClipboardContentFromMonitorProcessing'];
const clone = value => JSON.parse(JSON.stringify(value));
function settingsFor(patch, base = DEFAULTS) {
  if (!patch || typeof patch !== 'object' || Array.isArray(patch)) throw new Error('Choose valid clipboard preferences.');
  const out = { ...base };
  for (const key of Object.keys(patch)) {
    if (!Object.hasOwn(DEFAULTS, key)) throw new Error('Unknown clipboard preference.');
    const value = patch[key];
    if (key === 'enabled' || key === 'paused') { if (typeof value !== 'boolean') throw new Error('Choose an enabled or paused state.'); }
    else if (!Number.isInteger(value) || (key === 'maxItems' ? value < 20 || value > 500 : ![1, 7, 30, 90].includes(value))) throw new Error('Choose 20–500 entries and 1, 7, 30, or 90 retention days.');
    out[key] = value;
  }
  return out;
}
class ClipboardHistory {
  constructor({ dataDir, clipboard, ClipboardItem, safeStorage, platform = process.platform, onChange = () => {}, isBlocked = () => false, now = Date.now }) {
    this.dir = path.join(dataDir, 'clipboard-history'); this.clipboard = clipboard; this.ClipboardItem = ClipboardItem; this.safeStorage = safeStorage; this.platform = platform;
    this.onChange = onChange; this.isBlocked = isBlocked; this.now = now; this.settings = { ...DEFAULTS }; this.entries = []; this.queue = Promise.resolve(); this.epoch = 0; this.lastHash = ''; this.busy = false; this.error = ''; this.initialized = this.load();
  }
  available() { try { return !!this.safeStorage?.isEncryptionAvailable() && (this.platform !== 'linux' || ['gnome_libsecret', 'kwallet', 'kwallet5', 'kwallet6'].includes(this.safeStorage.getSelectedStorageBackend?.())); } catch { return false; } }
  async load() {
    let foundHistory = false, validPreferences = false;
    try { this.settings = settingsFor(JSON.parse(await fs.readFile(path.join(this.dir, 'preferences.json'), 'utf8'))); validPreferences = true; } catch (e) { if (e.code !== 'ENOENT') this.error = 'Clipboard preferences could not be loaded.'; }
    try {
      const bytes = await fs.readFile(path.join(this.dir, 'history.bin')); foundHistory = true;
      if (!this.available()) { this.error = 'Unlock your system secret store and restart to open saved clipboard history.'; this.loadFailed = true; return; }
      if (bytes.length > MAX_TOTAL * 1.5 || bytes.length < 29 || bytes[0] !== 1) throw new Error('Invalid history');
      const encryptedKey = await fs.readFile(path.join(this.dir, 'key.bin'));
      this.key = Buffer.from(this.safeStorage.decryptString(encryptedKey), 'base64');
      if (this.key.length !== 32) throw new Error('Invalid key');
      const decipher = crypto.createDecipheriv('aes-256-gcm', this.key, bytes.subarray(1, 13)); decipher.setAuthTag(bytes.subarray(13, 29));
      const saved = JSON.parse(Buffer.concat([decipher.update(bytes.subarray(29)), decipher.final()]).toString('utf8'));
      if (saved.version !== 1 || !Array.isArray(saved.entries) || saved.entries.length > 500) throw new Error('Invalid history');
      this.entries = saved.entries.map(entry => { this.validateEntry(entry); return entry; });
      if (saved.settings) this.settings = settingsFor(saved.settings);
      if (!validPreferences) {
        this.settings.enabled = false; this.preferencesRecovery = true;
        this.error = 'Clipboard preferences need review. Saved items were kept; choose your history preferences before capturing more.';
        return;
      }
    } catch (e) { if (e.code !== 'ENOENT' || foundHistory) { this.error = 'Saved clipboard history could not be decrypted. Existing files were kept.'; this.loadFailed = true; this.entries = []; } return; }
    const previous = this.entries;
    try { this.trim(); if (this.entries.length !== previous.length) await this.persist(); }
    catch { this.entries = previous; this.error = 'Saved clipboard history is open, but expiry cleanup could not be saved. It will be retried.'; }
  }
  validateEntry(entry) {
    if (!entry || typeof entry.id !== 'string' || !/^[0-9a-f-]{36}$/.test(entry.id) || !['text','image','files'].includes(entry.kind) || typeof entry.hash !== 'string' || typeof entry.pinned !== 'boolean' || !Number.isFinite(entry.createdAt) || !Number.isFinite(entry.size) || entry.size < 0 || entry.size > MAX_ITEM * 1.5) throw new Error('Invalid clipboard entry.');
    if (entry.kind === 'text' && (typeof entry.text !== 'string' || Buffer.byteLength(entry.text) > MAX_TEXT || (entry.html && (typeof entry.html !== 'string' || Buffer.byteLength(entry.html) > MAX_TEXT)))) throw new Error('Invalid clipboard text.');
    if (entry.kind === 'image') validateClipboardPNG(Buffer.from(entry.png, 'base64'));
    if (entry.kind === 'files') parseFileURIs(entry.files.map(file => pathToFileURL(file).href).join('\n'), this.platform);
  }
  trim() {
    const cutoff = this.now() - this.settings.retentionDays * 86400000;
    this.entries = this.entries.filter(e => e.pinned || e.createdAt >= cutoff);
    let bytes = this.entries.reduce((sum, entry) => sum + entry.size, 0);
    while (this.entries.length > this.settings.maxItems || bytes > MAX_TOTAL) {
      const index = this.entries.findLastIndex(e => !e.pinned); if (index < 0) throw new Error('Favourites fill the history limit. Unpin or remove an item first.');
      bytes -= this.entries[index].size; this.entries.splice(index, 1);
    }
  }
  async atomic(file, bytes) { const temporary = path.join(this.dir, crypto.randomUUID()+'.tmp'); try { await fs.writeFile(temporary, bytes, { mode: 0o600, flag: 'wx' }); await fs.rename(temporary, path.join(this.dir, file)); } finally { await fs.rm(temporary, { force: true }); } }
  async persist() {
    if (!this.available()) throw new Error('A secure system secret store is required for clipboard history.');
    if (this.loadFailed) throw new Error(this.error);
    await fs.mkdir(this.dir, { recursive: true, mode: 0o700 });
    if (!this.key) { const key = crypto.randomBytes(32); const wrapped = this.safeStorage.encryptString(key.toString('base64')); await this.atomic('key.bin', wrapped); this.key = key; }
    const encrypted = await new Promise((resolve, reject) => {
      const worker = new Worker(path.join(__dirname, 'history-storage-worker.cjs'), { workerData: { key: this.key, saved: { version: 1, settings: this.settings, entries: this.entries } } });
      let settled = false;
      worker.once('message', bytes => { settled = true; resolve(Buffer.from(bytes)); });
      worker.once('error', reject);
      worker.once('exit', code => { if (!settled) reject(new Error(`Clipboard storage worker stopped (${code}).`)); });
    });
    // The encrypted settings are authoritative; write the non-sensitive mirror first.
    await this.atomic('preferences.json', JSON.stringify(this.settings));
    await this.atomic('history.bin', encrypted);
  }
  snapshot({ query = '', filter = 'all' } = {}) {
    const needle = String(query).slice(0, 1000).toLowerCase();
    const entries = this.entries.filter(e => (filter === 'all' || (filter === 'pinned' ? e.pinned : e.kind === filter)) && (!needle || `${e.title}\n${e.text || ''}\n${(e.files || []).join('\n')}`.toLowerCase().includes(needle))).map(e => ({ id: e.id, kind: e.kind, title: e.title, preview: e.kind === 'text' ? e.text.slice(0, 220) : e.kind === 'files' ? e.files.map(f => path.basename(f)).join(', ').slice(0,220) : 'PNG image', pinned: e.pinned, createdAt: e.createdAt, lastUsedAt: e.lastUsedAt, size: e.size }));
    return { entries, settings: { ...this.settings }, available: this.available(), error: this.error || undefined };
  }
  async getState(options) { await this.initialized; return this.snapshot(options); }
  emit() { try { this.onChange(this.snapshot()); } catch {} }
  mutate(fn, { notify = true, returnState = true } = {}) {
    const task = this.queue.catch(() => {}).then(async () => {
      await this.initialized; const previous = this.entries.map(entry => ({ ...entry }));
      try { const value = await fn(); if (notify) this.emit(); return value ?? (returnState ? this.snapshot() : undefined); }
      catch (error) { this.entries = previous; throw error; }
    }); this.queue = task; return task;
  }
  updatePreferences(patch) {
    settingsFor(patch, this.settings); ++this.epoch;
    return this.mutate(async () => {
      if (this.loadFailed) throw new Error(this.error);
      const settings = settingsFor(patch, this.settings);
      if (settings.enabled && !this.available()) throw new Error('Unlock a secure system secret store before enabling clipboard history.');
      const previous = this.settings; this.settings = settings;
      try {
        this.trim(); await this.persist();
        this.preferencesRecovery = false; this.error = '';
      } catch (e) { this.settings = previous; throw e; }
    });
  }
  async readCurrent() {
    if (typeof this.clipboard?.has === 'function') for (const marker of MARKERS) if (await this.clipboard.has(`electron application/osclipboard;format="${marker}"`)) return null;
    const items = await this.clipboard.read();
    if (!Array.isArray(items) || items.length > 500) throw new Error('The clipboard contains too many items.');
    for (const item of items) if (item.types?.some(type => MARKERS.some(marker => type.includes(marker)))) return null;
    const find = type => items.find(item => item.types?.includes(type));
    const bytes = async (item, type, max) => { const blob = await item.getType(type); if (blob.size > max) throw new Error('This clipboard item is too large for history. Use the transfer shelf instead.'); const data = Buffer.from(await blob.arrayBuffer()); if (data.length > max) throw new Error('Clipboard size limit exceeded.'); return data; };
    const fileItems = items.filter(item => item.types?.includes('text/uri-list'));
    if (fileItems.length) {
      const lists = await Promise.all(fileItems.map(async item => (await bytes(item, 'text/uri-list', MAX_TEXT)).toString('utf8')));
      if (!lists.every(isNonFileURIList)) {
        const unique = [...new Set(lists.flatMap(list => parseFileURIs(list, this.platform)))];
        if (unique.length > 500) throw new Error('Copy at most 500 files.');
        return { kind: 'files', files: unique, title: unique.length === 1 ? path.basename(unique[0]) : `${unique.length} copied files` };
      }
    }
    const png = find('image/png'); if (png) return { kind: 'image', png: validateClipboardPNG(await bytes(png, 'image/png', MAX_ITEM)).toString('base64'), title: 'Copied image' };
    const plain = find('text/plain'); if (plain) { const text = (await bytes(plain, 'text/plain', MAX_TEXT)).toString('utf8'); if (!text) return null; const htmlItem = find('text/html'); const html = htmlItem ? (await bytes(htmlItem, 'text/html', MAX_TEXT)).toString('utf8') : undefined; return { kind: 'text', text, ...(html ? { html } : {}), title: text.replace(/\s+/g, ' ').slice(0, 80) }; }
    return null;
  }
  async store(content, { pinned = false, automatic = false } = {}) {
    if (this.preferencesRecovery) throw new Error(this.error);
    const hash = crypto.createHash('sha256').update(JSON.stringify([content.kind,content.text,content.html,content.png,content.files])).digest('hex');
    if (automatic && hash === this.lastHash) return false;
    const existing = this.entries.find(e => e.hash === hash);
    if (existing) { if (automatic && this.lastHash === hash) return false; this.entries = [existing, ...this.entries.filter(e => e.id !== existing.id)]; existing.lastUsedAt = this.now(); existing.pinned ||= pinned; if (pinned) existing.title = content.title; }
    else { const size = Buffer.byteLength(JSON.stringify(content)); const entry = { ...content, id: crypto.randomUUID(), hash, pinned, size, createdAt: this.now(), lastUsedAt: this.now() }; this.validateEntry(entry); this.entries.unshift(entry); }
    this.trim(); if (!this.entries.some(entry => entry.hash === hash)) throw new Error('Favourites fill the history limit. Unpin or remove an item first.'); await this.persist(); this.lastHash = hash; return true;
  }
  capture({ automatic = false } = {}) {
    const epoch = this.epoch;
    return this.mutate(async () => {
      if (automatic && (!this.settings.enabled || this.settings.paused || this.isBlocked() || epoch !== this.epoch)) return;
      if (!this.available()) throw new Error('Unlock a secure system secret store to save clipboard history.');
      if (this.loadFailed) throw new Error(this.error);
      const content = await this.readCurrent();
      if (automatic && (epoch !== this.epoch || this.isBlocked() || !this.settings.enabled || this.settings.paused)) return;
      if (!content) { if (!automatic) throw new Error('The clipboard is empty, unsupported, or marked private by its source app.'); return; }
      if (await this.store(content, { automatic })) this.emit();
    }, { notify: false, returnState: !automatic });
  }
  async tick() {
    await this.initialized;
    if (this.available() && !this.loadFailed && !this.preferencesRecovery && this.entries.some(e => !e.pinned && e.createdAt < this.now() - this.settings.retentionDays * 86400000)) await this.mutate(async () => { this.trim(); await this.persist(); }, { returnState: false });
    if (!this.settings.enabled || this.settings.paused || this.busy || this.isBlocked() || !this.available() || this.loadFailed) return;
    this.busy = true; try { await this.capture({ automatic: true }); } catch { /* Never emit clipboard contents or popup from a background read. */ } finally { this.busy = false; }
  }
  async detail(id) { await this.initialized; const e = this.entries.find(e => e.id === id); if (!e) throw new Error('This clipboard item is no longer available.'); return { id: e.id, kind: e.kind, title: e.title, ...(e.kind === 'text' ? { text: e.text, html: e.html } : e.kind === 'image' ? { imageDataURL: 'data:image/png;base64,'+e.png } : { files: [...e.files] }) }; }
  copy({ id, plainText = false }) {
    return this.mutate(async () => {
      const e = this.entries.find(entry => entry.id === id); if (!e) throw new Error('This clipboard item is no longer available.');
      const data = e.kind === 'text' ? { 'text/plain': new Blob([e.text], { type: 'text/plain' }), ...(!plainText && e.html ? { 'text/html': new Blob([e.html], { type: 'text/html' }) } : {}) } : e.kind === 'image' ? { 'image/png': new Blob([Buffer.from(e.png, 'base64')], { type: 'image/png' }) } : { 'text/uri-list': new Blob([e.files.map(file => pathToFileURL(file).href).join('\r\n')], { type: 'text/uri-list' }) };
      await this.clipboard.write([new this.ClipboardItem(data)]); this.lastHash = e.kind === 'text' && plainText ? crypto.createHash('sha256').update(JSON.stringify(['text',e.text,undefined,undefined,undefined])).digest('hex') : e.hash; e.lastUsedAt = this.now();
    });
  }
  setPinned({ id, pinned }) { return this.mutate(async () => { if (typeof pinned !== 'boolean') throw new Error('Choose a favourite state.'); const e = this.entries.find(entry => entry.id === id); if (!e) throw new Error('This clipboard item is no longer available.'); e.pinned = pinned; this.trim(); await this.persist(); }); }
  remove(id) { return this.mutate(async () => { this.entries = this.entries.filter(e => e.id !== id); await this.persist(); }); }
  clearUnpinned() { return this.mutate(async () => { this.entries = this.entries.filter(e => e.pinned); await this.persist(); }); }
  saveSnippet({ text, title = '' }) { return this.mutate(async () => { if (typeof text !== 'string' || !text.trim() || Buffer.byteLength(text) > MAX_TEXT) throw new Error('Enter a snippet up to 1 MB.'); if (typeof title !== 'string' || title.length > 120) throw new Error('Use a title up to 120 characters.'); await this.store({ kind: 'text', text, title: title.trim() || text.replace(/\s+/g,' ').slice(0,80) }, { pinned: true }); }); }
  async addToShelf(id, service) { const e = await this.detail(id); if (e.kind === 'text') return service.enqueueText(e.text); if (e.kind === 'files') return service.enqueueFiles(e.files); return service.enqueueClipboardImage(Buffer.from(e.imageDataURL.split(',')[1], 'base64')); }
}
module.exports = { ClipboardHistory, settingsFor, DEFAULTS, MAX_TOTAL };
