'use strict';
const { contextBridge, ipcRenderer, webUtils } = require('electron');
const invoke = (method, ...args) => ipcRenderer.invoke(`drift:${method}`, ...args);
const subscribe = (channel, callback) => {
  const listener = (_event, payload) => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
};
contextBridge.exposeInMainWorld('drift', {
  getReceived: () => invoke('getReceived'),
  refreshReceived: () => invoke('refreshReceived'),
  markReceivedRead: request => invoke('markReceivedRead', request),
  openReceivedFolder: request => invoke('openReceivedFolder', request),
  addReceivedToShelf: request => invoke('addReceivedToShelf', request),
  onReceived: callback => subscribe('drift:received', callback),
  getUpdates: () => invoke('getUpdates'),
  checkForUpdates: () => invoke('checkForUpdates'),
  updateUpdatePreferences: request => invoke('updateUpdatePreferences', request),
  downloadUpdate: () => invoke('downloadUpdate'),
  cancelUpdate: () => invoke('cancelUpdate'),
  installUpdate: () => invoke('installUpdate'),
  openUpdateRelease: () => invoke('openUpdateRelease'),
  revealUpdateDownload: () => invoke('revealUpdateDownload'),
  onUpdates: callback => subscribe('drift:updates', callback),
  productName: process.argv.includes('--lex-drift-product-name=LexBridge') ? 'LexBridge' : process.argv.includes('--lex-drift-product-name=lex-drift') ? 'lex-drift' : 'ShelfDock',
  confirmRendererReady: () => invoke('confirmRendererReady'),
  platform: (process.argv.find(a => a.startsWith('--lex-drift-platform=')) || '').split('=')[1] || 'unknown',
  updateClipboardTools: request => invoke('updateClipboardTools', request),
  getClipboardHistory: request => invoke('getClipboardHistory', request),
  updateClipboardPreferences: request => invoke('updateClipboardPreferences', request),
  captureClipboardHistory: request => invoke('captureClipboardHistory', request),
  getClipboardEntry: request => invoke('getClipboardEntry', request),
  copyClipboardEntry: request => invoke('copyClipboardEntry', request),
  setClipboardPinned: request => invoke('setClipboardPinned', request),
  removeClipboardEntry: request => invoke('removeClipboardEntry', request),
  clearClipboardHistory: request => invoke('clearClipboardHistory', request),
  saveClipboardSnippet: request => invoke('saveClipboardSnippet', request),
  addClipboardEntryToShelf: request => invoke('addClipboardEntryToShelf', request),
  onClipboardHistory: callback => subscribe('drift:clipboard-history', callback),
  updateClipboardSync: request => invoke('updateClipboardSync', request),
  pairOwnedClipboardSync: request => invoke('pairOwnedClipboardSync', request),
  updateClipboardPeer: request => invoke('updateClipboardPeer', request),
  revokeClipboardPeer: request => invoke('revokeClipboardPeer', request),
  getMacInstallState: () => invoke('getMacInstallState'),
  previewMacInstall: request => invoke('previewMacInstall', request),
  installOnMac: request => invoke('installOnMac', request),
  onMacInstallState: callback => subscribe('drift:mac-install', callback),
  getRemoteDesktopState: () => invoke('getRemoteDesktopState'),
  inspectRemoteDesktop: request => invoke('inspectRemoteDesktop', request),
  previewRemoteDesktopSetup: request => invoke('previewRemoteDesktopSetup', request),
  applyRemoteDesktopSetup: request => invoke('applyRemoteDesktopSetup', request),
  startRemoteDesktop: request => invoke('startRemoteDesktop', request),
  stopRemoteDesktop: request => invoke('stopRemoteDesktop', request),
  onRemoteDesktop: callback => subscribe('drift:remote-desktop', callback),
  getRemoteInstallState: () => invoke('getRemoteInstallState'),
  previewRemoteInstall: request => invoke('previewRemoteInstall', request),
  installRemotely: request => invoke('installRemotely', request),
  cancelRemoteInstall: request => invoke('cancelRemoteInstall', request),
  onRemoteInstall: callback => subscribe('drift:remote-install', callback),
  getTunnels: () => invoke('getTunnels'),
  startTunnel: request => invoke('startTunnel', request),
  openTunnelSite: request => invoke('openTunnelSite', request),
  copyTunnelSite: request => invoke('copyTunnelSite', request),
  stopTunnel: id => invoke('stopTunnel', id),
  restartTunnel: id => invoke('restartTunnel', id),
  removeTunnelHistory: id => invoke('removeTunnelHistory', id),
  updateTunnelNote: request => invoke('updateTunnelNote', request),
  onTunnels: callback => subscribe('drift:tunnels', callback),
  getState: () => invoke('getState'),
  refreshHosts: () => invoke('refreshHosts'),
  probeHosts: request => invoke('probeHosts', request),
  configureAccess: request => invoke('configureAccess', request),
  forgetPassword: hostId => invoke('forgetPassword', hostId),
  saveHost: host => invoke('saveHost', host),
  removeHost: id => invoke('removeHost', id),
  enqueueFiles: paths => invoke('enqueueFiles', paths),
  enqueueText: text => invoke('enqueueText', text),
  removeItem: id => invoke('removeItem', id),
  clearItems: () => invoke('clearItems'),
  undoClear: () => invoke('undoClear'),
  sendMany: request => invoke('sendMany', request),
  send: request => invoke('send', request),
  updateSettings: patch => invoke('updateSettings', patch),
  setInteraction: value => invoke('setInteraction', value),
  captureClipboard: () => invoke('captureClipboard'),
  exportConfig: () => invoke('exportConfig'),
  importConfig: () => invoke('importConfig'),
  pickFiles: () => invoke('pickFiles'),
  hideWindow: () => invoke('hideWindow'),
  quit: () => invoke('quit'),
  openSettingsFolder: () => invoke('openSettingsFolder'),
  getFilePath: file => webUtils.getPathForFile(file),
  onState: callback => subscribe('drift:state', callback),
  onReveal: callback => subscribe('drift:reveal', callback),
});
